### ISSUE TITLE
Memory writing issue

### ISSUE THREAD

**Issue by JTPernu** [kevinmcaleer/pca9685_for_pico#2]
There's an issue with writing to memory, it seems. Gives this error comand, even with the demo:

Traceback (most recent call last):
  File "<stdin>", line 11, in <module>
  File "/lib/pca9685_for_pico/pca9685.py", line 29, in __init__
  File "/lib/pca9685_for_pico/pca9685.py", line 39, in reset
  File "/lib/pca9685_for_pico/pca9685.py", line 32, in _write
OSError: [Errno 5] EIO

**Comment by thethoughtfulinventor** [comment]
Have you found a soluton to this? I am also having the same issue.

**Comment by gokul6350** [comment]
yaaa me too

**Comment by gokul6350** [comment]
> Have you found a soluton to this? I am also having the same issue.

have you found it works some but doesn't work some times .

**Comment by thethoughtfulinventor** [comment]
I have found a solution. the code is a few years out of date, so one of the things you need to do is replace all the Pin() lines with machine.Pin(). this fixed the error for me, however you do need to make sure that your i2c device is connected to the pins you set in the code.

**Comment by thethoughtfulinventor** [comment]
having said that, i am now getting an error saying that the Servos commands arent there.

**Comment by JTPernu** [comment]
>  replace all Pin() lines with machine.Pin()

This shouldn't actually make a difference. At least the current file imports machine.Pin() in a way, that just saying Pin() includes the library already: _from machine import I2C, Pin_

**Comment by JTPernu** [comment]
> Have you found a soluton to this? I am also having the same issue.

I indeed have, it seems. I forgot entirely to update this, so I apologize for that. The issue was, if I'm not entirely mistaken, pretty silly. 

You have to look at the Servo.py file, and either fix the import statement or name the pca9685.py to pca.py. Looks like the author forgot to rename it, or just plain named it wrong by mistake. Fixing it worked for me at least.

**Comment by JTPernu** [comment]
> Have you found a soluton to this? I am also having the same issue.

I have, I guess. It's a fiddly thing, it looks like, but the problem can be solved by rebooting the pico, I think. Or reconnect to it. I haven't a clue how, but I did get it to work with that. But do make sure to fix the import statement from Servo.py.

**Comment by gokul6350** [comment]
your 

> > Have you found a soluton to this? I am also having the same issue.
> 
> I have, I guess. It's a fiddly thing, it looks like, but the problem can be solved by rebooting the pico, I think. Or reconnect to it. I haven't a clue how, but I did get it to work with that. But do make sure to fix the import statement from Servo.py.

can i get your discord

**Comment by thethoughtfulinventor** [comment]
i have gotten everything working now, i just needed to restart the pico, however its not moving the motors.

**Comment by thethoughtfulinventor** [comment]
> your
> 
> > > Have you found a soluton to this? I am also having the same issue.
> > 
> > 
> > I have, I guess. It's a fiddly thing, it looks like, but the problem can be solved by rebooting the pico, I think. Or reconnect to it. I haven't a clue how, but I did get it to work with that. But do make sure to fix the import statement from Servo.py.
> 
> can i get your discord

is this to me or them?

**Comment by JTPernu** [comment]
> your
> 
> > > Have you found a soluton to this? I am also having the same issue.
> > 
> > 
> > I have, I guess. It's a fiddly thing, it looks like, but the problem can be solved by rebooting the pico, I think. Or reconnect to it. I haven't a clue how, but I did get it to work with that. But do make sure to fix the import statement from Servo.py.
> 
> can i get your discord

If you mean me, mind if I ask why?

**Comment by JTPernu** [comment]
> i have gotten everything working now, i just needed to restart the pico, however its not moving the motors.

Does it give you any error message? Or is it just not moving? If the former, please show us the message, if the latter, please show the code. I can try and help you solve it, if you need help

**Comment by thethoughtfulinventor** [comment]
this is all the code in the main.py:
#from pca9685 import PCA9685
# from picocat import Servos
from machine import I2C, Pin
from servo import Servos
sda = machine.Pin(4)
scl = machine.Pin(5)

i2c = I2C(0, sda=sda, scl=scl)

#pca = PCA9685(i2c=i2c)
# pca.i2c = i2c
servo = Servos(i2c=i2c)
servo.position(index=0, degrees=180)

**Comment by thethoughtfulinventor** [comment]
idk why it formatted like that tho

**Comment by JTPernu** [comment]
> this is all the code in the main.py: #from pca9685 import PCA9685
> # from picocat import Servos
>
> from machine import I2C, Pin from servo import Servos sda = machine.Pin(4) scl = machine.Pin(5)
>
> i2c = I2C(0, sda=sda, scl=scl)
>
> #pca = PCA9685(i2c=i2c)
> # pca.i2c = i2c
> 
> servo = Servos(i2c=i2c) servo.position(index=0, degrees=180)

Hmmmm... Looks like you're putting the pca.py into comments, so that might be it. And 
`pca=PCA9685(i2c=i2c) ` is commented too.

Bet beyond that, you can always scan four i2c, if the code finds the device at all:
_devices = i2c.scan(
if len(devices) != 0:
     print('Number of I2C devices found=',len(devices))
     for device in devices:
         print("Device Hexadecimel Address= ",hex(device))
     print()
 else:
    print("No I2C device found")_


If you want, here's my test code. You can try with that. I use different pins and file name, so do change those in the code before trying.


![Code Snip](https://github.com/kevinmcaleer/pca9685_for_pico/assets/125442777/c256e77a-db4d-4db3-870a-3d0db514ee71)

**Comment by gokul6350** [comment]
> i have gotten everything working now, i just needed to restart the pico, ho

because its hard to talk here it will better if we discuss there

**Comment by gokul6350** [comment]
any permanent way to fix the error @JTPernu  @thethoughtfulinventor  
Gokul#9638 - Discord

**Comment by thethoughtfulinventor** [comment]
maybe, i wont know untill friday or monday tho. i let out the magic smoke by accident

**Comment by thethoughtfulinventor** [comment]
> any permanent way to fix the error @JTPernu @thethoughtfulinventor Gokul#9638 - Discord

welp, i just installed the program on the new pico, and it works just fine. my guess is that you guys need to reintall micropython on your bords.

**Comment by JustAnotherMakerChannel** [comment]
The solution for me was to change the import in servo.py

# CHANGE SERVO.PY IMPORT FROM
from pca import PCA9685

# CHANGE SERVO.PY IMPORT TO
from pca9685 import PCA9685

and also to change the __init__ code

# CHANGE SERVO.PY __INIT__ FROM
def __init__(self, i2c, address=0x40, freq=50, min_us=600, max_us=2400,
                 degrees=180):
        self.period = 1000000 / freq
        self.min_duty = self._us2duty(min_us)
        self.max_duty = self._us2duty(max_us)
        self.degrees = degrees
        self.freq = freq
        self.pca9685 = PCA9685(i2c, address)
        self.pca9685.freq(freq)

# CHANGE SERVO.PY __INIT__ TO
def __init__(self, pca, freq=50, min_us=600, max_us=2400,
                 degrees=180):
        self.period = 1000000 / freq
        self.min_duty = self._us2duty(min_us)
        self.max_duty = self._us2duty(max_us)
        self.degrees = degrees
        self.freq = freq
        self.pca9685 = pca
        self.pca9685.freq(freq)

and when you initialise everything in your code it looks like this

# Initialize I2C
i2c = I2C(0, scl=Pin(21), sda=Pin(20))

# Initialize Servos
pca = PCA9685(i2c)
servos = Servos(pca)


Hope this helps someone :)
